// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKhAMCeugu906I6_W4tXMneLgK2MiLrdk',
    appId: '1:496113701296:web:3dde60e52a363a9a0fc675',
    messagingSenderId: '496113701296',
    projectId: 'lolplatform-eb04b',
    authDomain: 'lolplatform-eb04b.firebaseapp.com',
    storageBucket: 'lolplatform-eb04b.appspot.com',
    measurementId: 'G-W7MZMG7H7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9Xg0vtDoT_55rnJ4Nr6Gubl2R_Bn2aY',
    appId: '1:496113701296:android:33d142c100a532be0fc675',
    messagingSenderId: '496113701296',
    projectId: 'lolplatform-eb04b',
    storageBucket: 'lolplatform-eb04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCj8EwsJ280jQRclLTXjpbtTEYv81pY0',
    appId: '1:496113701296:ios:95dd1a2276a4ee350fc675',
    messagingSenderId: '496113701296',
    projectId: 'lolplatform-eb04b',
    storageBucket: 'lolplatform-eb04b.appspot.com',
    iosBundleId: 'com.example.lolplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYCj8EwsJ280jQRclLTXjpbtTEYv81pY0',
    appId: '1:496113701296:ios:95dd1a2276a4ee350fc675',
    messagingSenderId: '496113701296',
    projectId: 'lolplatform-eb04b',
    storageBucket: 'lolplatform-eb04b.appspot.com',
    iosBundleId: 'com.example.lolplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKhAMCeugu906I6_W4tXMneLgK2MiLrdk',
    appId: '1:496113701296:web:31ae518c021ffb6d0fc675',
    messagingSenderId: '496113701296',
    projectId: 'lolplatform-eb04b',
    authDomain: 'lolplatform-eb04b.firebaseapp.com',
    storageBucket: 'lolplatform-eb04b.appspot.com',
    measurementId: 'G-ZKSK3JZG2Q',
  );
}
